spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/demoappdb
    username: demoappuser
    password: demoapp123
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
