server:
  port: 8085

spring:
  application:
    name: api-gateway
  codec:
    max-in-memory-size: 20MB
  webflux:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: knowledge-base-service-route
          uri: lb://knowledge-base-service
          predicates:
            - Path=/api/conversations/**
        - id: roadmap-service-route
          uri: lb://roadmap-service
          predicates:
            - Path=/api/roadmaps/**
        - id: interview-simulator-route
          uri: lb://interview-simulator
          predicates:
            - Path=/api/interview/**,/api/topics/**,/api/mcq-test/**,/api/coding/**,/api/repository/**,/api/documents/**,/api/chat/**,/api/resume/**,/api/manipulation-categories/**,/api/complexity-categories/**
        - id: asknehru-backend-route
          uri: lb://asknehru-backend
          predicates:
            - Path=/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
